{*************************************************}
{                                                 }
{  Blaise 4 Windows. A Survey Processing System   }
{  Copyright (c) 1992,2002 Statistics Netherlands }
{                                                 }
{*************************************************}

{ This file contains the allowed keyboard short-cut's }
{ for menu definitions                                }

TYPE TFunctionKey =
   ({F1 (1) "f1",  not supported}
    F2 (2) "f2",
    F3 (3) "f3",
    F4 (4) "f4",
    F5 (5) "f5",
    F6 (6) "f6",
    F7 (7) "f7",
    F8 (8) "f8",
    F9 (9) "f9",
    F10 (10) "f10",
    AltF1 (11) "altf1",
    AltF2 (12) "altf2",
    AltF3 (13) "altf3",
    AltF4 (14) "altf4",
    AltF5 (15) "altf5",
    AltF6 (16) "altf6",
    AltF7 (17) "altf7",
    AltF8 (18) "altf8",
    AltF9 (19) "altf9",
    AltF10 (20) "altf10",
    CtrlF1 (21) "ctrlf1",
    CtrlF2 (22) "ctrlf2",
    CtrlF3 (23) "ctrlf3",
    CtrlF4 (24) "ctrlf4",
    CtrlF5 (25) "ctrlf5",
    CtrlF6 (26) "ctrlf6",
    CtrlF7 (27) "ctrlf7",
    CtrlF8 (28) "ctrlf8",
    CtrlF9 (29) "ctrlf9",
    CtrlF10 (30) "ctrlf10",
    ShiftF1 (31) "shiftf1",
    ShiftF2 (32) "shiftf2",
    ShiftF3 (33) "shiftf3",
    ShiftF4 (34) "shiftf4",
    ShiftF5 (35) "shiftf5",
    ShiftF6 (36) "shiftf6",
    ShiftF7 (37) "shiftf7",
    ShiftF8 (38) "shiftf8",
    ShiftF9 (39) "shiftf9",
    ShiftF10 (40) "shiftf10",
    {CtrlA (41) "ctrla",  not supported}
    CtrlB (42) "ctrlb",
    {CtrlC (43) "ctrlc",  not supported}
    {CtrlD (44) "ctrld",  not supported}
    {CtrlE (45) "ctrle",  not supported}
    {CtrlF (46) "ctrlf",  not supported}
    {CtrlG (47) "ctrlg",  not supported}
    {CtrlH (48) "ctrlh",  not supported}
    CtrlI (49) "ctrli",
    CtrlJ (50) "ctrlj",
    CtrlK (51) "ctrlk",
    CtrlL (52) "ctrll",
    CtrlM (53) "ctrlm",
    CtrlN (54) "ctrln",
    CtrlO (55) "ctrlo",
    CtrlP (56) "ctrlp",
    CtrlQ (57) "ctrlq",
    {CtrlR (58) "ctrlr",  not supported}
    {CtrlS (59) "ctrls",  not supported}
    CtrlT (60) "ctrlt",
    CtrlU (61) "ctrlu",
    {CtrlV (62) "ctrlv",  not supported}
    CtrlW (63) "ctrlw",
    {CtrlX (64) "ctrlx",  not supported}
    CtrlY (65) "ctrly",
    CtrlZ (66) "ctrlz",
    Alt0 (67) "alt0",
    Alt1 (68) "alt1",
    Alt2 (69) "alt2",
    Alt3 (70) "alt3",
    Alt4 (71) "alt4",
    Alt5 (72) "alt5",
    Alt6 (73) "alt6",
    Alt7 (74) "alt7",
    Alt8 (75) "alt8",
    Alt9 (76) "alt9",
    AltA (77) "alta",
    AltB (78) "altb",
    AltC (79) "altc",
    AltD (80) "altd",
    AltE (81) "alte",
    AltF (82) "altf",
    AltG (83) "altg",
    AltH (84) "alth",
    AltI (85) "alti",
    AltJ (86) "altj",
    AltK (87) "altk",
    AltL (88) "altl",
    AltM (89) "altm",
    AltN (90) "altn",
    AltO (91) "alto",
    AltP (92) "altp",
    AltQ (93) "altq",
    AltR (94) "altr",
    AltS (95) "alts",
    AltT (96) "altt",
    AltU (97) "altu",
    AltV (98) "altv",
    AltW (99) "altw",
    AltX (100) "altx",
    AltY (101) "alty",
    AltZ (102) "altz")
